travis:
  secure:
    BINSTAR_TOKEN: RxL6ZMzLczGFwfNbNxcyRPZzHS/68WGJ0z0axzE/33I2aJSCBrl0v4LogpjgNZ8HfjrqYPVBYfQtdi1/YlxMdVIGrrx4Uu2KhUMft8qLOW/hDcWUOQvxkBFKDAYHBSvodaqTZExvJDtAxThXvltHEIumHgSwXcqnVSPQ3wRLr4XZbEcEZ08oSKTWgsoH0xkh8b4LO6xrEWznyq3ZrwfvTOGUh3wcQyMwwDDXsZPAY/IlkG8yDASLqd/o6FwO4N+Lk4v8+OTnYwwr+I0wI2b/d2VSmdINQVJca/af9VHP/1e0oAz2E/iJAyCcRbP/M6vu/wj4AwyjxUz1Jrlj3gu5E9+K5aNOATJNBU/VQIxwJ60HmrbIfgQW9jrMwZMHZ5+qDdmNVXdQtSFJYW7yaOyQhU9iIgLhfHqm3YahG9XIYddhF0i0mRDqp6wO9P5wnTuxYpDoWEVaXObClcxjYuVIVc3/50juc/D5jy57tSEiyMyQlTkV20HUADo1MmpqdsPRosNT1rsiQnS+nc/q374h0z7mqvshspVOOa5ZOXcoq/Xr0WlVva0rhXHfh2q3NknZ+z38ullKoJCb7o7f6lYjRJii7wzXp9ApDdaVP/jFB0KmcKD0c+eBZIyaXZiyvCnoiIh9LiGCUiH7kGYhm6nKfyIcmhge3pIeI1loWaXZqQs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
